### ISSUE TITLE
license_proxy.exe

### ISSUE THREAD

**Issue by tamplin** [WHTJEON/narrowvine#2]
ucrtbased.dll error
vcruntime140d.dll error
when i download them 
0xc000007b
the` license_proxy.exe` can't run

**Comment by WHTJEON** [comment]
As you can see, it's caused because you don't have the proper libraries installed. 

Download and unzip [32bit.zip](https://github.com/WHTJEON/narrowvine/files/6438020/32bit.zip) to `..\Windows\System32` and download and unzip [64bit.zip](https://github.com/WHTJEON/narrowvine/files/6438018/64bit.zip) to `..\Windows\SysWOW64. 

That will do.

**Comment by tamplin** [comment]
> As you can see, it's caused because you don't have the proper libraries installed.
> 
> Download and unzip [32bit.zip](https://github.com/WHTJEON/narrowvine/files/6438020/32bit.zip) to `..\Windows\System32` and download and unzip [64bit.zip](https://github.com/WHTJEON/narrowvine/files/6438018/64bit.zip) to `..\Windows\SysWOW64.
> 
> That will do.

that wokring

**Comment by Mavrick007** [comment]
im getting same error

**Comment by WHTJEON** [comment]
> im getting same error, VCRUNTIME140D.dll & ucrtbased.dll is missing can someone help plz

The solutions are clearly stated in BOTH the README File and ISSUEs. Please read before asking
